exports.MovieList = [
    'Blue Jasmine',
    'Annie Hall',
    'The Irishman',
    'Taxi Driver',
    'Gangs of New York',
    'GoodFellas',
    'Sin City',
    'The Departed',
    'The Wolf of Wall Street',
    'Kill Bill: Vol. 2',
    'Inglourious Basterds',
    'Cape Fear',
    'The Hateful Eight',
    'Reservoir Dogs',
    'Death Proof',
    'Django Unchained',
    'Vicky Cristina Barcelona',
    'Eyes Wide Shut',
    'The Wild Pear Tree',
    'Midnight in Paris',
    'The Favourite',
    'Winter Sleep',
    'Shutter Island',
    'The Godfather: Part III',
    'Full Metal Jacket',
    'Manhattan',
    'Psycho',
    'Rear Window',
    'Hugo',
    'Once Upon a Time in Anatolia',
    'The Godfather: Part II',
    'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    'Spartacus',
    'A Clockwork Orange',
    'The Conversation',
    'Casino',
    'The Birds',
    'Dial M for Murder',
    'Once Upon a Time in America',
    'For a Few Dollars More',
    'The Godfather',
    'The Good, the Bad and the Ugly',
    'Pacific Rim',
    'Once Upon a Time… in Hollywood',
    'A Fistful of Dollars',
    'Hellboy',
    'eXistenZ',
    'Silence',
    'The Aviator',
    'Dead Ringers',
    'Raging Bull',
    'The Lobster',
    'The Killing of a Sacred Deer',
    'The King of Comedy',
    'Mean Streets',
    "Before the Devil Knows You're Dead",
    'Fantastic Mr. Fox',
    'Corpse Bride',
    'Dumbo',
    '2001: A Space Odyssey',
    'Kill Bill: Vol. 1',
    'Batman',
    'The Shining',
    'Jackie Brown',
    'A History of Violence',
    'Pulp Fiction',
    'The Skin I Live In',
    'Dogtooth',
    'Inside Man',
    'Once Upon a Time in the West',
    'The Shape of Water',
    'Malcolm X',
    'Snowpiercer',
    'The Grand Budapest Hotel',
    'Lolita',
    'The Nightmare Before Christmas',
    'Barry Lyndon',
    'Paths of Glory',
    'Breaking the Waves',
    'Mission: Impossible',
    'The Revenant',
    'Das Boot',
    'Blade',
    'Vertigo',
    'Rope',
    'North by Northwest',
    'Memories of Murder',
    'The Untouchables',
    'Eastern Promises',
    'Biutiful',
    'Videodrome',
    'Parasite',
    'Babel',
    'Amores Perros',
    'Edward Scissorhands',
    'Nightmare Alley',
    "Pan's Labyrinth",
    'The Fly',
    'Murder on the Orient Express',
    '12 Angry Men',
    'House of Gucci',
    'Dog Day Afternoon',
    'American Gangster',
    'The Dead Zone',
    'Blade Runner',
    'Serpico',
    'The French Dispatch',
    'The Big Lebowski',
    'Life of Brian',
    'Monty Python and the Holy Grail',
    'Bridge of Spies',
    'Charlie and the Chocolate Factory',
    'Fargo',
    'Kingdom of Heaven',
    'Stalker',
    'Antichrist',
    'Alice in Wonderland',
    'Melancholia',
    'The Thin Red Line',
    'The Verdict',
    'Do the Right Thing',
    'Twelve Monkeys',
    'Burn After Reading',
    'Inside Llewyn Davis',
    'Scarface',
    'BlacKkKlansman',
    'Mirror',
    'The Sacrifice',
    'The Pianist',
    "Carlito's Way",
    'Insomnia',
    'Dunkirk',
    'Roma',
    'Children of Men',
    '21 Grams',
    'Pain and Glory',
    '25th Hour',
    'Birdman or (The Unexpected Virtue of Ignorance)',
    'No Country for Old Men',
    'Interstellar',
    'Batman Begins',
    'Alien',
    'The Dark Knight',
    'Alien: Covenant',
    'The Girl with the Dragon Tattoo',
    'Black Hawk Down',
    'Memento',
    'The Game',
    'Fight Club',
    'Andrei Rublev',
    'The Duellists',
    'Breathless',
    'The Martian',
    'Masculin Féminin',
    'Gladiator',
    'Chinatown',
    'The Last Duel',
    'Barton Fink',
    'Touch of Evil',
    'Prometheus',
    'Mulholland Drive',
    'La Dolce Vita',
    'True Grit',
    'There Will Be Blood',
    "Rosemary's Baby",
    'Blue Velvet',
    'The Tree of Life',
    'Carnage',
    'The Master',
    'Enemy',
    'Dune',
    'Solaris',
    "Ivan's Childhood",
    'The Ninth Gate',
    'Punch-Drunk Love',
    'Inherent Vice',
    'Tenet',
    'The Gold Rush',
    'Harry Potter and the Prisoner of Azkaban',
    'Se7en',
    'Nostalgia',
    'Sicario',
    'Modern Times',
    'Gravity',
    'The Kid',
    'City Lights',
    'The Dark Knight Rises',
    'Inception',
    'Catch Me If You Can',
    'Panic Room',
    'The Prestige',
    'Scenes from a Marriage',
    'Lincoln',
    'Zodiac',
    'Jurassic Park',
    'Minority Report',
    'Citizen Kane',
    'Amistad',
    'The Curious Case of Benjamin Button',
    "Schindler's List",
    'Lost Highway',
    'Saving Private Ryan',
    'The Social Network',
    'Yojimbo',
    'Seven Samurai',
    'Gone Girl',
    '8½',
    'Magnolia',
    'Ikiru',
    'Mank',
    'The Lady from Shanghai',
    'Throne of Blood',
    'Rashomon',
    'Blade Runner 2049',
    'Dogville',
    'Dancer in the Dark',
    'The Elephant Man',
    'Dune',
    'Eraserhead',
    'Boogie Nights',
    'Wild Strawberries',
    'The Great Dictator',
    'Phantom Thread',
    'Cries and Whispers',
    'Incendies',
    'War of the Worlds',
    'Prisoners',
    'Arrival',
    'The Circus',
    'Jaws',
    'Empire of the Sun',
    'The Seventh Seal',
    'Persona',
    'Ran',
    'Kagemusha',
    'Raiders of the Lost Ark',
    'Munich',
    'Hour of the Wolf',
    'War Horse'
]
